name: CI/CD 
on:
    push:
        branches: ["*"]
        paths-ignore: 
            - "README.md"
            - "docs/**"
    pull_request:
        branches: [master]
        paths-ignore:
            - "README.md"
            - "docs/**"
jobs: 
    all-cli-checks: 
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./apps/app
        steps:
            - uses: actions/checkout@v6.0.1
            - uses: actions/setup-node@v6.1.0
              with: 
                node-version: lts/*

            - name: Set environment variables
              run: mv .env.example .env

            - name: Install dependencies
              run: pnpm install

            - name: Run linter
              run: pnpm check

            - name: Fix errors
              run: pnpm fix

            - name: Check types
              run: pnpm typecheck

            - name: Build application
              run: pnpm build

            - name: Run tests
              run: pnpm test

    e2e: 
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
            run: 
                working-directory: ./apps/app
        steps:
            - uses: actions/checkout@v6.0.1
            - uses: actions/setup-node@v6.1.0
              with: 
                node-version: lts/*

            - name: Set environment variables
              run: mv .env.example-e2e .env

            - name: Install dependencies
              run: npm install -g pnpm

            - name: Install Playwright Browsers
              run: pnpm install playwright --with-deps

            - name: Run Playwright tests
              run: pnpm test-e2e
            
            - uses: actions/upload-artifact@v5.0.0
              if: always()
              with: 
                name: playwright-report
                path: |
                  playwright-report/
                  mocked-db.json
                retention-days: 30
